# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 18:44
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='send', max_length=100, no_check_for_status=True),
        ),
    ]
