# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20160405_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='theme',
            new_name='subject',
        ),
    ]
