# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 21:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0003_auto_20160520_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(related_name='message_recipients', to=settings.AUTH_USER_MODEL),
        ),
    ]
