# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('al_jazeera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aljazeerapost',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
