# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 00:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_remove_facebookpost_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
