# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0004_auto_20160331_0719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookpost',
            options={'ordering': ('-created',)},
        ),
    ]
