# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160330_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/static/images/avatar.jpg', upload_to=''),
        ),
    ]
