# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbcpost',
            name='short_text',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
