# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbc', '0002_bbcpost_short_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbcpost',
            name='tag',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
